name: webhook workflow 

on:
  repository_dispatch:
    types: [webhook]

jobs:
  respond_to_dispatch:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2 
      - name: Run a script 
        run: echo "Event of type: $GITHUB_EVENT_NAME"
